server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cwm3/spring-cloud-examples/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 389317866@qq.com                                         # git仓库的账号
          password: c033022011                                         # git仓库的密码
